### ISSUE TITLE
Basic indentation Tracking

### ISSUE THREAD

**Issue by lwgray** [lwgray/thinkpy#21]
# Basic Indentation Tracking
**Level: Padawan**

## Description
Add basic indentation tracking to the ThinkPy parser to support indentation-based syntax while maintaining backward compatibility with braces.

### Changes Needed in parser.py

1. Add new token definitions:
```python
tokens = tokens + (
    'INDENT',
    'DEDENT',
    'NEWLINE'
)
```

2. Add indentation tracking to ThinkPyParser class:
```python
def __init__(self):
    self.indent_stack = [0]  # Track indentation levels
    self.current_line = 1    # Track line numbers
    # ... existing init code ...
```

3. Add lexer rules for whitespace tracking:
```python
def t_NEWLINE(self, t):
    r'\n+'
    t.lexer.lineno += len(t.value)
    return t

def t_space(self, t):
    r'[ \t]+'
    if t.lexer.lexpos == 0:  # Start of line
        spaces = len(t.value.expandtabs(4))
        if spaces > self.indent_stack[-1]:
            t.type = 'INDENT'
            self.indent_stack.append(spaces)
            return t
```

### Test Case 1: Basic Indentation
```python
objective "Test"

task "Simple"
    x = 1
```
Expected token stream:
```
OBJECTIVE "Test" NEWLINE
TASK "Simple" NEWLINE INDENT
IDENTIFIER EQUALS NUMBER NEWLINE
DEDENT
```

### Test Case 2: Empty Lines and Comments
```python
objective "Test"
# Comment
task "Simple"
    # Indented comment
    x = 1

```
Should handle empty lines and comments correctly.

### Test Case 3: Mixed Indentation Levels
```python
task "Mixed"
    x = 1
        y = 2  # This should raise an error
```
Should detect inconsistent indentation.

## Completion Criteria
1. [ ] New tokens are defined and recognized
2. [ ] Indentation stack correctly tracks levels
3. [ ] INDENT tokens generated for increased indentation
4. [ ] DEDENT tokens generated for decreased indentation
5. [ ] NEWLINE tokens handled properly
6. [ ] All test cases pass
7. [ ] Backward compatibility with brace syntax maintained
8. [ ] Documentation updated with new token information

## Dependencies
None - this is a foundational change

## Documentation Updates Needed
- Add section on indentation rules to language reference
- Update parser documentation with new tokens
- Add examples of proper indentation

## Testing Instructions
1. Run the provided test cases
2. Verify token stream output
3. Check error handling for inconsistent indentation
4. Validate backward compatibility with braced syntax
