### ISSUE TITLE
Step and Subtask Without Braces

### ISSUE THREAD

**Issue by lwgray** [lwgray/thinkpy#24]
# Step and Subtask Without Braces
**Level: Knight**

## Description
Update parser to support indentation-based step and subtask definitions, handling nested structures and return values appropriately.

### Changes Needed in parser.py

1. Update step grammar:
```python
def p_step(self, p):
    """
    step : STEP STRING NEWLINE INDENT statement_list DEDENT
         | STEP STRING LBRACE statement_list RBRACE
    """
    p[0] = {
        'type': 'step',
        'name': p[2],
        'statements': p[4] if len(p) == 6 else p[4],
        'line': p.lineno(1)
    }
```

2. Update subtask grammar:
```python
def p_subtask(self, p):
    """
    subtask : SUBTASK STRING NEWLINE INDENT statement_list DEDENT
            | SUBTASK STRING LBRACE statement_list RBRACE
    """
    p[0] = {
        'type': 'subtask',
        'name': p[2],
        'statements': p[4] if len(p) == 6 else p[4],
        'line': p.lineno(1)
    }
```

3. Update return statement handling:
```python
def p_return_statement(self, p):
    """
    return_statement : RETURN expression NEWLINE
    """
    p[0] = {
        'type': 'return',
        'value': p[2],
        'line': p.lineno(1)
    }
```

### Test Case 1: Basic Step
```python
step "Basic"
    x = 1
    y = 2
```

### Test Case 2: Basic Subtask with Return
```python
subtask "Calculate"
    x = 1
    y = 2
    return x + y
```

### Test Case 3: Nested Structures
```python
task "Main"
    step "Outer"
        x = 1
        step "Inner"
            y = 2
    subtask "Helper"
        return x + y
```

### Test Case 4: Multiple Returns (Invalid)
```python
subtask "Invalid"
    return 1
    return 2  # Should raise error
```

### Test Case 5: Empty Structures
```python
step "Empty"
    # Should raise error

subtask "Empty"
    # Should raise error
```

### Test Case 6: Mixed Indentation Levels
```python
task "Mixed"
    step "Level1"
        x = 1
            y = 2  # Should raise error
    subtask "Level1"
        return x
```

## Completion Criteria
1. [ ] Parser recognizes indentation-based step definitions
2. [ ] Parser recognizes indentation-based subtask definitions
3. [ ] Return statements properly handled
4. [ ] Nested structures work correctly
5. [ ] Empty structures detected and reported
6. [ ] Invalid indentation detected
7. [ ] Multiple returns detected and reported
8. [ ] Line numbers tracked correctly
9. [ ] All test cases pass
10. [ ] Backward compatibility maintained

## Dependencies
- Issue #21 : Basic Indentation Tracking
- Issue #22 : Enhanced Newline Handling
- Issue #23 : Task Definition Without Braces

## Documentation Updates Needed
- Update step/subtask syntax documentation
- Document return statement rules
- Add examples of valid/invalid structures
- Update nesting guidelines
- Document indentation rules for nested structures

## Testing Instructions
1. Run provided test cases
2. Verify AST structure
3. Test error handling
4. Validate nested structures
5. Check return statement handling
6. Test backward compatibility
7. Verify error messages

## Migration Notes
- Old brace syntax will continue working
- New code should use indentation syntax
- Both syntaxes supported during transition
- Migration tool will be provided later

## Error Message Examples
```python
# Invalid nesting
Error: Inconsistent indentation at line 3
Expected indentation level 2, found level 3

# Multiple returns
Error: Multiple return statements in subtask at line 4
Subtasks should have only one return statement

# Empty structure
Error: Empty step/subtask body at line 2
Steps and subtasks must contain at least one statement
```
